version: 'v3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 1337:8000
    env_file:
      - ./.env

  db:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=museum_bot
      - POSTGRES_PASSWORD=museum_bot
      - POSTGRES_DB=museum_db

volumes:
  postgres_data: