  version: '3.8'

  services:
    web:
      build:
        context: .
        dockerfile: Dockerfile.prod
      command: gunicorn Core.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - static_volume:/home/app/web/staticfiles
      env_file:
        - ./.env
      depends_on:
        - db
    db:
      image: postgres:16.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        POSTGRES_DB: msc_db
        POSTGRES_USER: msc_bot
        POSTGRES_PASSWORD: msc_bot
      ports:
        - "${DB_PORT:-1338}:5432"
    nginx:
      build: ./nginx
      volumes:
        - static_volume:/home/app/web/staticfiles
      ports:
        - "${NGINX_PORT:-1337}:80"
      depends_on:
        - web

  volumes:
    postgres_data:
    static_volume: