# Generated by Django 4.1.7 on 2024-09-11 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст правильного ответа')),
                ('photo', models.ImageField(blank=True, upload_to='staticfiles/questions/photo/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Комментарий к ответам',
                'verbose_name_plural': 'Комментарии к ответам',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='answer_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='museum_bot.answerdescription', verbose_name='Комментарий к ответам'),
        ),
    ]
