# Generated by Django 4.1.7 on 2024-09-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_bot', '0002_answerdescription_question_answer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermuseumprogression',
            name='hint_used',
            field=models.BooleanField(default=False, verbose_name='Использована подсказка?'),
        ),
    ]
