# Generated by Django 4.1.7 on 2024-09-11 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum_bot', '0005_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperGameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.BooleanField(default=False, verbose_name='На вопрос 1 ответил корректно?')),
                ('question2', models.BooleanField(default=False, verbose_name='На вопрос 1 ответил корректно?')),
                ('question3', models.BooleanField(default=False, verbose_name='На вопрос 1 ответил корректно?')),
                ('winner', models.BooleanField(default=False, verbose_name='Победил в супер-игре?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum_bot.tguser', verbose_name='Пользователь')),
            ],
        ),
    ]
