# Generated by Django 4.1.7 on 2024-09-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msr_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategoryprogression',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, upload_to='questions/file/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.ImageField(blank=True, upload_to='questions/photo/'),
        ),
    ]
