# Generated by Django 4.1.7 on 2024-09-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msr_bot', '0003_alter_usercategoryprogression_questions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='answer', max_length=255),
            preserve_default=False,
        ),
    ]
