# Generated by Django 4.1.7 on 2024-09-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msr_bot', '0005_useranswer_answer_useranswer_text_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
