# Generated by Django 4.1.7 on 2024-09-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msr_bot', '0007_alter_answer_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, upload_to='static/questions/file/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/questions/photo/'),
        ),
    ]
