# Generated by Django 4.1.7 on 2024-09-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msr_bot', '0008_alter_question_file_alter_question_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, upload_to='staticfiles/questions/file/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.ImageField(blank=True, upload_to='staticfiles/questions/photo/'),
        ),
    ]
